import { useState } from 'react'
import NavBar from './NavBar'

function Header() {
    // modificar este componente
    return (
        <>
            <NavBar />
            <section className='bg-fondo min-h-screen'>
                <h1 className='text-center text-6xl font-semibold font-body pt-32'>
                    <span className='text-blanco'>Time</span>
                    <span className='text-principal'>Crystal</span>
                    </h1>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
                    <p className='text-secundario'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero voluptates quisquam, accusamus dignissimos dolorem quaerat quasi eum corrupti praesentium dicta culpa asperiores est ducimus vitae reiciendis iste voluptatum dolore doloribus.</p>
            </section>
        </>
    )
}

export default Header